# Site settings
title: 죽이되든 밥이되든
email: blacktmt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm testing the Jekyll blog.
  I'm not a programer
  It's not that easy to do this. I'm doing just step by step, very slowly.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emotionmate.github.io" # the base hostname & protocol for your site
twitter_username: blacktmt
github_username:  Emotionmate

# Build settings
permalink: pretty

markdown: redcarpet

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap